services:
  php-fpm:
    build: .
    container_name: php-fpm
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
      - ./conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - internal

  nginx:
    image: nginx:1.26
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - internal

  postgres:
    image: postgres:16.3
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - internal
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

networks:
  internal:
    driver: bridge
